"""Manifests for community checkpoints: repo-root models and files the repo lacks. No network."""

import json

from eidolon_models_laya.artifacts import Manifest, sha256_file, verify_torch
from eidolon_models_laya.config import Settings


def _manifest(tmp_path, *, subfolder, generated=None):
    weights = tmp_path / "torch" / "model.safetensors"
    weights.parent.mkdir(parents=True)
    weights.write_bytes(b"weights")
    raw = {
        "name": "t",
        "source": {"repo_id": "someone/model", "subfolder": subfolder, "revision": "abc"},
        "torch": {"dir": "torch", "files": {"model.safetensors": sha256_file(weights)}},
        "onnx": {"dir": "onnx", "file": "model.onnx", "opset": 18},
    }
    if generated is not None:
        raw["torch"]["generated"] = generated
    (tmp_path / "manifest.json").write_text(json.dumps(raw))
    return Manifest.load(tmp_path)


def test_repo_root_checkpoint_has_empty_subfolder(tmp_path):
    assert _manifest(tmp_path, subfolder="").subfolder == ""
    assert Manifest(tmp_path, {"source": {"repo_id": "r", "revision": "x"}}).subfolder == ""


def test_generated_config_is_verified_by_content(tmp_path):
    cfg = {"encoder": "jhu-clsp/mmBERT-base", "head_layers": 2, "head_max_len": 512}
    m = _manifest(tmp_path, subfolder="", generated={"rl_agent_config.json": cfg})
    assert any("generated by fetch" in p for p in verify_torch(m))

    path = m.torch_dir / "rl_agent_config.json"
    path.write_text(json.dumps(cfg, indent=2))  # formatting may differ, content must not
    assert verify_torch(m) == []

    path.write_text(json.dumps({**cfg, "head_max_len": 256}))
    assert any("differs" in p for p in verify_torch(m))


def test_head_max_len_override():
    assert Settings.from_env({}).head_max_len is None
    assert Settings.from_env({"EIDOLON_LAYA_HEAD_MAX_LEN": "1024"}).head_max_len == 1024


def test_hub_defaults_to_huggingface(tmp_path):
    assert _manifest(tmp_path, subfolder="").hub == "huggingface"
    m = Manifest(tmp_path, {"source": {"repo_id": "r", "revision": "x", "hub": "modelscope"}})
    assert m.hub == "modelscope"


def test_modelscope_fetch_streams_each_file_and_checks_sha(tmp_path, monkeypatch):
    import io

    from eidolon_models_laya import artifacts

    m = _manifest(tmp_path, subfolder="")
    m.raw["source"]["hub"] = "modelscope"
    (m.torch_dir / "model.safetensors").unlink()
    urls = []

    def fake_urlopen(url, timeout):
        urls.append(url)
        return io.BytesIO(b"weights")

    monkeypatch.setattr(artifacts.urllib.request, "urlopen", fake_urlopen)
    artifacts.fetch_torch(m, log=lambda *_: None)
    assert urls == [
        "https://www.modelscope.cn/api/v1/models/someone/model/repo?Revision=abc&FilePath=model.safetensors"
    ]
    assert verify_torch(m) == []
    assert not list(m.torch_dir.glob("*.part"))

    (m.torch_dir / "model.safetensors").unlink()
    monkeypatch.setattr(
        artifacts.urllib.request, "urlopen", lambda url, timeout: io.BytesIO(b"tampered")
    )
    try:
        artifacts.fetch_torch(m, log=lambda *_: None)
    except RuntimeError as e:
        assert "sha256" in str(e)
    else:
        raise AssertionError("tampered download was accepted")
